### ISSUE TITLE
[0.0.0]Aplicacion Crashea Cuando regresa de la ventana de seleccion de avatar sin seleccionar imagen

### ISSUE THREAD

**Issue by CoCoNO** [CoCoNO/VIWP#1]
Abrir aplicacion
Iniciar sesion
vas a perfil
toque en editar
cambiar imagen
regresar sin seleccionar imagen

Crash report:

An exception of type 'System.InvalidCastException' occurred in VoyIteso.DLL but was not handled in user code

Additional information: Unable to cast object of type 'System.Windows.Controls.TextBox' to type 'System.Windows.Controls.TextBlock'.

Call Stack

>   VoyIteso.DLL!VoyIteso.Pages.ProfilePage.OnNavigatedTo(System.Windows.Navigation.NavigationEventArgs e) Line 205 C#

**Comment by python48** [comment]
I'll take a look at it asap!

**Comment by python48** [comment]
fixed
