### ISSUE TITLE
The first time the app is run it crashes

### ISSUE THREAD

**Issue by python48** [CoCoNO/VIWP#21]
the app crashes the very first time that is run on a WP device

**Comment by AlfredoFausto** [comment]
the app still crashes...
09/10/2015

**Comment by CoCoNO** [comment]
Post steps to replicate problem

Enviado por Outlook para Android

On Tue, Nov 10, 2015 at 9:54 AM -0800, "Alfredo Fausto" notifications@github.com wrote:
the app still crashes...

---

**Comment by python48** [comment]
@CoCoNO  any news on this?

**Comment by python48** [comment]
Now it has milestone, uh. There I charge on you! @CoCoNO  @AlfredoFausto

**Comment by python48** [comment]
STEPS TO REPLICATE PROBLEM:
Start app, 
Sign as a new user (need student account please help),
Chose whatever option (driver or passenger),

> > There is your ERROR, when the main menu has loaded. 
> > @CoCoNO

**Comment by AlfredoFausto** [comment]
@CoCoNO please attend to the task

**Comment by python48** [comment]
I believe I fixed the problem, but I will leave the issue open cus I haven't tested. (need empty account)

**Comment by CoCoNO** [comment]
Done and dusted.

Problem was that the home page tried to get the first notification when there is none

Fixed on 9cc50931062eb478867ac18df62088db16ce0066
