### ISSUE TITLE
Orthography check

### ISSUE THREAD

**Issue by python48** [CoCoNO/VIWP#57]
The app needs to be double checked for orthography mistakes.

-assure that the app has no mistakes with orthography.

**Comment by python48** [comment]
I did double check,

**Comment by AlfredoFausto** [comment]
Arreglar faltas de ortografía en el Message Box, al crear nueva ruta y pedir aventon

**Comment by python48** [comment]
ya quedo eso, falta q le demos una ultima checada para ver si ya cerramos este "issue"

**Comment by python48** [comment]
se le corrigieron las faltas a la regla de que debemos comenzar un dialogo con mayusculas siempre. En cualquier componente grafico. hay q revisar los encabezados de las paginas para ver si modificamos ahi tambien siguiendo esta regla. ahi te encargo Alfredo (?), hay q ver esto mañana.

**Comment by python48** [comment]
done
