### ISSUE TITLE
"Ver puntos" feature failure

### ISSUE THREAD

**Issue by python48** [CoCoNO/VIWP#73]
The app gets himself killed when trying to view the points of the route of a specific person.

**Comment by python48** [comment]
Necesito que me ayudes a resolver esto, Mike me devuelve un arreglo diferente al tuyo y con diferente sintaxis. Hoy encárgate de ayudarme con esto por favor, y con otra cosa que al rato te digo. @CoCoNO

**Comment by python48** [comment]
Cuando llegues al lab me marcas para explicarte el problema. @CoCoNO

**Comment by python48** [comment]
It seemed to be a server-side problem :S

**Comment by CoCoNO** [comment]
Arreglado en b33178cb708d12c8d4276ad2e626bd1f85e52451

**Comment by python48** [comment]
Take a look at the following debug:

![image](https://cloud.githubusercontent.com/assets/5482308/11416268/aeb0520c-93d1-11e5-9c91-f1bef2748b21.png)

The array "puntos_intermedios" is null,

**Comment by CoCoNO** [comment]
Not our problem, that is and old entry
