### ISSUE TITLE
Lost internet connection (app crashes)

### ISSUE THREAD

**Issue by AlfredoFausto** [CoCoNO/VIWP#75]
When loading a request if the internet connection is lost, the app crashes and close unexpectedly

**Comment by python48** [comment]
@cocono

**Comment by python48** [comment]
we'll check it out! @CoCoNO, take a look at this.

**Comment by AlfredoFausto** [comment]
ASAP

**Comment by python48** [comment]
We have to set milestones from now own. @AlfredoFausto

**Comment by python48** [comment]
On*

**Comment by CoCoNO** [comment]
On it

**Comment by CoCoNO** [comment]
Its all the request, if you lose connection while a request is being procesed it will crash all the app

**Comment by CoCoNO** [comment]
Solucion poner try catch en todas las peticiones al apiconector que sean asincronas y mostrar un mensaje de error

**Comment by python48** [comment]
the calls to apiconnector are now under try catch statements
