### ISSUE TITLE
Filtros en "Pedir aventón"

### ISSUE THREAD

**Issue by AlfredoFausto** [CoCoNO/VIWP#76]
No entiendo el funcionamiento de trabajo de los filtros en el apartado de "pedir aventón"
Si yo soy el fumador, pero al que le pedi ride no fuma, porque me sale en los resultados.

**Comment by python48** [comment]
Porque esos filtros no son considerados en en los parámetros. Creo que así funciona el api. Hay q preguntarle q Mike

**Comment by python48** [comment]
Jairo me explicó que no filtra, mañana veámoslo junto con el.

**Comment by python48** [comment]
@CoCoNO

**Comment by CoCoNO** [comment]
Mike no pregunta si queres fumador o fumador a la hora de buscar, se supone que se basa en las configuraciones del perfil

**Comment by python48** [comment]
Sugiero que escondamos los filtros para que quede igualita a la de Android.

**Comment by CoCoNO** [comment]
https://scontent-dfw1-1.xx.fbcdn.net/hphotos-xtp1/v/t34.0-12/12312140_1203919509637118_282364526_n.jpg?oh=ee22929989bfb9b913a09db2589c75ca&oe=56589F1C Mike no los usa en la app mobil

**Comment by python48** [comment]
por cierto, nuestra interfaz se ve más bonita. :+1:

**Comment by AlfredoFausto** [comment]
En teoría sí deberíamos de quitarlos, pero mas vale preguntarle a mike
