### ISSUE TITLE
Ortografía (última revisión)

### ISSUE THREAD

**Issue by AlfredoFausto** [CoCoNO/VIWP#77]
- Menú principal app bar tiene que ser "Cerrar sesión" sin mayuscula en la segunda palabra y acento
- En buscar ruta en los recuadros, "Buscar dirección" falta acentro en dirección.
- Cuando un aventón es solicitado, se recorta al decir "Ha sido aceptado el aventón"
- En el chat en vez de decir "tú" en la imagen tiene que decir "Yo"
- Verificar en los tutoriales mayúsculas y minusculas.

**Comment by python48** [comment]
ya quedo
