### ISSUE TITLE
Calificar aventón

### ISSUE THREAD

**Issue by AlfredoFausto** [CoCoNO/VIWP#78]
El checkbox se lanza de manera infinita al calificar un aventón.

Cuando el aventón ha sido calificado, se manda un mensaje de que no ha sido posible calificar el aventón.

**Comment by python48** [comment]
I stumbled upon a new technical problem with the IDE (Problem of the week @AlfredoFausto )

After updating Windows 10 to build 10061 windows phone emulators (all 8.1 and 10) stopped starting. I get the following error: "Windows Phone Emulator is unable to connect to the Windows Phone operating system. Couldn`t setup the UDP port"
Hyper-V manager shows that virtual machine works, and it can be started directly from Hyper-V manager. 

These are the steps for a solution:
Run cmd as admin and enter the following commands
set devmgr_show_nonpresent_devices=1
start devmgmt.msc
This will startup the device manager and show the list of hyper v network adapters
Right click and uninstall all hyper v network adapters
Open Hyper v manager and delete the virtual machines
From Virtual Switch Manager (right side of hyper-v manager), delete all internal switches
Restart the system and run visual studio and launch emulator

See this for more info http://www.gfi.com/blog/how-to-remove-hidden-network-adapters-from-virtual-machines/

**Comment by python48** [comment]
solved in 025d95f13881f2cdf93be62f7031a562c9a4922b
