### ISSUE TITLE
Calendar profile missing

### ISSUE THREAD

**Issue by CoCoNO** [CoCoNO/VIWP#79]
when oppening a lift on the calendar you cant open a profile

**Comment by python48** [comment]
Will check it out.

**Comment by python48** [comment]
Please help!! @CoCoNO 
Server is NOT responding properly>> Unable to cast object of type 'System.String' to type 'System.Collections.Generic.IDictionary`2[System.String,System.Object]'."

**Comment by python48** [comment]
???

**Comment by CoCoNO** [comment]
Line 141 De route info variable Fromcalendar siempre va a ser falsa

**Comment by python48** [comment]
fetch Dev9

**Comment by CoCoNO** [comment]
Fixed in 535f9fba89b37bb0eddaa45d55a1e4f2d757fcc7
